Feature/sort newslist
snack-news/Snack-BE pull request #125
Opened 2019-11-24 07:46 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- 조회 기준을 생성일(createAt)이 아닌 예약일(publishAt)으로 변경
- 예약일에 기본값(생성일) 할당
- mock 데이터에 예약일에 대한 정보 추가
- 원소의 순서를 보장 리스트를 검증하기 위한 커스텀 matcher 추가

2019-11-24 11:13 UTC, NESOY requested changes

2019-11-24 11:13 UTC, NESOY commented on src/main/java/com/snack/news/domain/news/News.java
> +		this.publishAt = Objects.nonNull(publishAt) ? publishAt : LocalDateTime.now();
`null`이 발생하는 케이스는 어느 경우일까요?

2019-11-24 11:13 UTC, NESOY commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +			criteria.add(builder.lessThan(nr.get("publishAt"), newsDto.getEndDateTime()));
음.. 변수명이 여기서 MagicNumber로 존재하면 변수명 바꾸기 힘들거 같은데 더 좋은 방법이 없을까요?

2019-11-24 11:13 UTC, NESOY commented on src/test/java/com/snack/news/repository/NewsRepositoryTest.java
> +		System.out.println(expectedResultNewsList);
```suggestion

```

2019-11-24 11:13 UTC, NESOY commented on src/test/java/com/snack/news/repository/NewsRepositoryTest.java
> +		System.out.println(actualResultNewsIdList);
```suggestion
```

2019-11-24 11:14 UTC, NESOY commented
@Delf-Lee 추가적으로 Spring 2.2.0에서는 Junit5를 사용하셔도 됩니다. :)

2019-11-25 00:27 UTC, Delf-Lee commented on src/main/java/com/snack/news/domain/news/News.java
> +		this.publishAt = Objects.nonNull(publishAt) ? publishAt : LocalDateTime.now();
뉴스 생성시 예약일이 없는경우입니다.

2019-11-25 10:18 UTC, Delf-Lee commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +			criteria.add(builder.lessThan(nr.get("publishAt"), newsDto.getEndDateTime()));
modelgen을 이용한다면 다음과 같이 변경할 수 있을겁니다.
``` java
criteria.add(builder.lessThan(nr.get("createAt"), newsDto.getEndDateTime())); // before
criteria.add(builder.lessThan(nr.get(News_.publishAt), newsDto.getEndDateTime())); // after
```
하지만 QueryDSL로 넘어갈 예정이기에 불필요한 구현일 수도 있다고 생각합니다. 어떻게 생각하시나요?

- Reference
   - https://www.baeldung.com/hibernate-criteria-queries-metamodel

2019-11-25 10:20 UTC, Delf-Lee commented
@Nesoy
Commit Suggestion은 한번에 변경하여 올리겠습니다.

2019-11-25 10:25 UTC, NESOY commented on src/test/java/com/snack/news/matcher/EqualsInOrder.java
> +
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Document empty method body](https://app.codacy.com/app/snack-news/Snack-BE/pullRequest?prid=4554850)

2019-11-25 10:25 UTC, NESOY commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/main/java/com/snack/news/domain/news/News.java  2
- src/test/java/com/snack/news/matcher/EqualsInOrder.java  4
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Snack-BE/Snack-BE/pullRequest?prid=4554850&bid=15320066)

2019-11-25 12:02 UTC, NESOY commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/Snack-BE/Snack-BE/pullRequest?prid=4554850&bid=15320066)

2019-11-25 12:14 UTC, Delf-Lee commented
@NESOY 테스트에 이상이 발견되어 추가로 수정했으니 리뷰 부탁드립니다.

조회 기준에 예약일이 추가됨으로써 쿼리에 "현재 시간"이 포함되게 되었습니다. 때문에 시간에 종속적이게 되었고 시간을 따로 주입할 수 있는 메서드를 추가하였습니다.

```
src/main/java/com/snack/news/repository/NewsRepositoryCustom.java
src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
src/test/java/com/snack/news/repository/NewsRepositoryTest.java
```

2019-11-25 12:15 UTC, Delf-Lee commented
pull하고 생각난 방법입니다만, 아예 NewsDto에 조회시간이라는 필드를 생성하고 기본값으로 현재시간, 필요할 때에 주입. 이라는 형식도 나쁘지 않아보이네요.

2019-11-26 15:32 UTC, NESOY commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +			criteria.add(builder.lessThan(nr.get("publishAt"), newsDto.getEndDateTime()));
QueryDSL로 넘어갈 예정이시면 불필요한 작업으로 보입니다 :)

2019-11-26 15:35 UTC, NESOY requested changes

2019-11-26 15:35 UTC, NESOY commented on src/test/java/com/snack/news/repository/NewsRepositoryTest.java
> +		System.out.println(actualResultNewsIdList);
제거해주세요 :)

2019-11-26 21:43 UTC, Delf-Lee commented
@NESOY 다른 문제가 없다면 merge해주세요.

2019-11-26 21:48 UTC, NESOY commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- src/test/java/com/snack/news/matcher/EqualsInOrder.java  4
- src/main/java/com/snack/news/domain/news/News.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/app/Snack-BE/Snack-BE/pullRequest?prid=4554850&bid=15320066)

2019-11-27 08:34 UTC, merged