Feature/newsinfinityscroll
snack-news/Snack-BE pull request #160
Opened 2020-01-22 04:24 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- 조회만을 위한 RuquestNewsDto 정의, NewsDto 삭제
- 무한스크롤을 위한 로직 변경
   - peried 검증 변경
   - criteria 쿼리 로직 변경 (임의의 id 이전의 값만 가져오도록, 일정 개수만 가져오도록)
   - 클라이언트에 뉴스 리스트를 담아 응답할 ListCursorResult를 따로 정의

2020-01-22 10:18 UTC, NESOY requested changes

2020-01-22 10:18 UTC, NESOY commented on src/main/java/com/snack/news/dto/ListCursorResult.java
> +public class ListCursorResult<R> {
@Delf-Lee 
Generic에서는 보통 T를 사용하는 것으로 알고 있는데
혹시 R로 선언하신 이유가 있으실까요?

2020-01-22 10:18 UTC, NESOY commented on src/main/java/com/snack/news/dto/Period.java
> +		if (end != null && start.isAfter(end)) {
생성 시점이 아니라 따로 method로 추출하신 이유가 있을까요?

2020-01-22 10:18 UTC, NESOY commented on src/main/java/com/snack/news/dto/Period.java
> +		if (end != null && start.isAfter(end)) {
end값이 null이여도 start.isAfter에서는 false로 반환하지 않을까요?

2020-01-22 10:18 UTC, NESOY commented on src/main/java/com/snack/news/service/NewsService.java
> +		return new ListCursorResult<>(newsList, hasNext(newsList));
음.. 굉장히 직접 만드신 느낌이드네요..
JPA Level에서 우리가 고민하고 있는 주제 Pageable에 대한 솔루션이 없을까요?

2020-01-22 10:18 UTC, NESOY commented on src/test/java/com/snack/news/controller/NewsControllerTest.java
> +		void requestNewsListTest() throws Exception {
인덴트 조정 부탁드릴게요 :)

2020-01-22 10:18 UTC, NESOY commented on src/test/java/com/snack/news/repository/NewsRepositoryTest.java
> +				() -> assertThat(originNewsList.size()).isNotEqualTo(limitNewsSize),
👍

2020-01-22 10:18 UTC, NESOY commented on src/test/java/com/snack/news/repository/NewsRepositoryTest.java
> +	@Transactional
매번 선언하기 귀찮은 경우 Spring의 `@DirtiesContext`도 참고하시면 좋을거 같네요 :)

2020-01-22 10:30 UTC, Delf-Lee commented on src/main/java/com/snack/news/dto/ListCursorResult.java
> +public class ListCursorResult<R> {
특별한 의미는 없었지만 덕분에 명명 규칙을 신경쓰게됐네요. 수정하겠습니다.
- https://codedragon.tistory.com/4567

2020-01-22 10:31 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/NewsService.java
> +		return new ListCursorResult<>(newsList, hasNext(newsList));
고민하고 있는부분입니다. 이슈화해서 다뤄볼까 생각중입니다.

2020-01-22 10:36 UTC, Delf-Lee commented on src/main/java/com/snack/news/dto/Period.java
> +		if (end != null && start.isAfter(end)) {
최초에 고민했던 문제가 여기서 풀리는군요!

AdminNewsDto와 RequestNewsDto를 분리되었으니, 각 parameter에 대한 validation도 독립적으로 가져갈 수 있게 되었습니다. 이 검증을 따로 DTO 안으로 넣거나, 생성자에서 관리할수 있게 된 것 같네요.

추가로 저 두 클래스들도 좋은 이름으로 바꿀 수 있을 것 같습니다.

2020-01-22 10:52 UTC, Delf-Lee commented on src/main/java/com/snack/news/dto/Period.java
> +		if (end != null && start.isAfter(end)) {
@NESOY 
end에 null이 허용되는건 현재 의도된 스펙입니다. 대신 limitSize를 설정하여 가져올 수 있는 최대 기사의 개수를 조절하였습니다.

2020-01-22 10:58 UTC, Delf-Lee commented on src/test/java/com/snack/news/repository/NewsRepositoryTest.java
> +	@Transactional
참고하겠습니다!

2020-01-22 10:59 UTC, Delf-Lee commented on src/test/java/com/snack/news/controller/NewsControllerTest.java
> +		void requestNewsListTest() throws Exception {
수정했습니다

2020-01-22 11:08 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/NewsService.java
> +		return new ListCursorResult<>(newsList, hasNext(newsList));
#161

2020-01-27 03:49 UTC, NESOY commented on src/main/java/com/snack/news/controller/AdminController.java
> +	public ResponseEntity<Wrapper<AdminNewsDto>> createNews(@Valid @RequestBody AdminNewsDto newsDto) {
`ResponseEntity<Wrapper<List<News>>>` 요것보다는
ResponseEntity<Wrapper>를 합친 하나의 컬렉션을 만드는건 어떠신가요?

2020-01-27 07:46 UTC, Delf-Lee commented
`ResponseEntity<Wrapper<?>>>` 감추기

2020-01-29 05:09 UTC, NESOY approved these changes

2020-01-31 22:23 UTC, merged