Picks Create/Read API
snack-news/Snack-BE pull request #165
Opened 2020-02-02 02:16 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- Picks의 create API와 read API가 추가되었습니다
- 대체로 news API와 유사합니다

2020-02-02 02:48 UTC, NESOY requested changes
- 변경사항이 너무 많아서 commit 단위로 리뷰했습니다.
- Pick의 Tag가 삭제된 이유가 있을까요?
- Git rebase를 활용하면 임시 Commit와 같은 경우 의미있는 커밋으로 바꿀 수 있을거 같아요.

2020-02-02 02:48 UTC, NESOY commented on build.gradle
> +    useJUnitPlatform()
어떤 역할로 추가하신지 알 수 있을까요?

2020-02-02 02:48 UTC, NESOY commented on src/main/java/com/snack/news/controller/NewsController.java
> +	public WrappedResponse<List<News>> getNewsList(@ModelAttribute @Valid RequestInquiryDto newsDto) {
`Inquiry`를 추가하신 이유가 어떤걸까요? 

질의면 `Query`가 더 명확하지 않을까요?

2020-02-02 02:48 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
업로드 도중에 중간에 실패하면 전체가 롤백이 될텐데 이게 맞는 스펙일까요?
아니면 부분실패를 해서 실패한 결과를 반환하는 방법도 있지않을까요?

2020-02-02 02:48 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +				categoryService.getCategory(pickDto.getCategoryId()),
하나의 트랙잭션에 add와 다른 서비스의 select가 여러개 있는 상황인데 과연 하나의 트랜잭션이라고 보장할 수 있을까요? 아니라면 이를 해결하기 위해 어떻게 해야할까요?

2020-02-02 02:48 UTC, NESOY commented on src/main/java/com/snack/news/service/PicksService.java
> +	private <E> E getLastElementInList(List<E> list) {
이런건 Util 클래스를 추가해서 Refactoring하시는건 어떠신가요?

2020-02-02 02:48 UTC, NESOY commented on src/test/java/com/snack/news/controller/AdminControllerTest.java
> +		mockMvc.perform(post(ADMIN_API_URL + "/news")
ADMIN_API_URL + "/news"가 여러개 있는데 URL을 Generate할 수 있는 클래스가 있으면 어떨까요?

2020-02-02 02:48 UTC, NESOY commented on src/test/java/com/snack/news/controller/AdminControllerTest.java
> +				.andExpect(status().isOk());
값에 대한 검증은 없을까요?

2020-02-02 02:48 UTC, NESOY commented on src/test/java/com/snack/news/service/AdminServiceTest.java
> +	@ValueSource(ints = {1, Integer.MAX_VALUE})
잘못된 Pick의 index가 들어오는 경우 대한 테스트도 있으면 좋겠네요 👍 
ex) index가 -1인 경우

2020-02-02 02:48 UTC, NESOY commented on src/test/java/com/snack/news/service/PicksServiceTest.java
> +//		when(picksRepository.findById(any())).thenReturn(Optional.of(Pick.builder().build()));
제거해주세요 :)

2020-02-02 02:52 UTC, Delf-Lee commented
@NESOY 
PIcks의 Tag는 원래 스펙상 존재하지 않았는데 Category와 헷갈려서 실수로 넣었었습니다 😅 
위의 실수를 포함해서 reabase를 활용해서 더 깔끔한 commit 관리에 신경써야겠군요.

2020-02-02 02:56 UTC, Delf-Lee commented on build.gradle
> +    useJUnitPlatform()
개발 환경을 윈도우로 바꾸면서 프로젝트가 Unit5 테스트를 인지하지 못해서 명시적으로 넣어준 구문이었습니다.
지금 삭제하니 정상 구동하네요... 조금 더 알아봐야겠습니다. 해당 구문은 삭제하겠습니다.

2020-02-02 02:59 UTC, Delf-Lee commented on src/test/java/com/snack/news/controller/AdminControllerTest.java
> +				.andExpect(status().isOk());
그건 서비스 레이어의 단위테스트 내지는 통합테스트에서의 역할이라고 생각합니다.
그런 점에서 아직까지 통합테스트가 없는건 아쉽네요

2020-02-02 03:12 UTC, Delf-Lee commented on build.gradle
> +    useJUnitPlatform()
fixed

2020-02-02 03:17 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/NewsController.java
> +	public WrappedResponse<List<News>> getNewsList(@ModelAttribute @Valid RequestInquiryDto newsDto) {
fixed

2020-02-02 03:24 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/PicksService.java
> +	private <E> E getLastElementInList(List<E> list) {
fixed

2020-02-02 03:25 UTC, Delf-Lee commented on src/test/java/com/snack/news/service/PicksServiceTest.java
> +//		when(picksRepository.findById(any())).thenReturn(Optional.of(Pick.builder().build()));
fixed

2020-02-02 03:27 UTC, Delf-Lee commented on src/test/java/com/snack/news/service/AdminServiceTest.java
> +	@ValueSource(ints = {1, Integer.MAX_VALUE})
fixed

2020-02-02 03:28 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
전체가 롤백이 되는건 맞다고 생각합니다. 
다만 영재님 말대로 사용자를 위해 실패한 결과를 알려주면 더 친절한 API가 될 것 같네요.

2020-02-02 03:29 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/AdminService.java
> +				categoryService.getCategory(pickDto.getCategoryId()),
고민하고 있는 부분입니다.
#121 과 연관된 이슈입니다.  같이 다루도록 하겠습니다.

2020-02-02 03:29 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/PicksService.java
> +	private <E> E getLastElementInList(List<E> list) {
fixed

2020-02-02 03:30 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
News bulk upload 구현시 같이 해결하겠습니다

2020-02-02 13:44 UTC, Delf-Lee commented on src/test/java/com/snack/news/controller/AdminControllerTest.java
> +		mockMvc.perform(post(ADMIN_API_URL + "/news")
fixed

2020-02-02 14:04 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
@Delf-Lee 
만약에 1000건 중에 1개라도 실패하면 전체 실패 진행되는건가요?

2020-02-02 14:05 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +				categoryService.getCategory(pickDto.getCategoryId()),
@Delf-Lee 
이해를 못해서 그러는뎅.. 어느 부분이 연관된 이슈인건가요?
@Transactional 내부 속성값을 참고하시면 될거 같아요 :)

2020-02-02 14:07 UTC, NESOY commented on src/test/java/com/snack/news/controller/AdminControllerTest.java
> +				.andExpect(status().isOk());
@Delf-Lee 통합테스트를 작성하는건 어려울까요?

2020-02-02 14:09 UTC, NESOY requested changes
Comment 추가했습니다. :)

2020-02-02 14:11 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
REST API 멱등성
- https://meetup.toast.com/posts/218

2020-02-02 14:58 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
@NESOY 
한개라도 이상이 있을시 전체 실패합니다. 실패 메시지는 어떻게 던질지 고민이군요

2020-02-02 15:08 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/AdminService.java
> +				categoryService.getCategory(pickDto.getCategoryId()),
@NESOY 
#121 에서 news add를 하기 위해 세번 select를 하는 구문이 중복이라는 점에서였습니다.

"하나의 트랜잭션이라고 보장한다" 라는 의미가 뭔가요? "하나의 트랜잭션으로 묶어도 되는가?" 라는 의미인가요?

2020-02-03 10:27 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +	@Transactional
@Delf-Lee 
기획이나 FE분들이랑 논의하고 결정하는 것도 나쁘지 않아보여요 ㅎㅎ

2020-02-03 10:31 UTC, NESOY commented on src/main/java/com/snack/news/service/AdminService.java
> +				categoryService.getCategory(pickDto.getCategoryId()),
@Delf-Lee 
`하나의 트랜잭션으로 묶지 않으면 이슈가 발생하지 않을까?` 
select, save 하나의 트랜잭션이지만 Annotation은 Save에만 존재하고
select쪽이 트랜잭션이 전파가 안되서 보장이 안될거 같아서 리뷰 남겨드렸습니다.

2020-02-04 00:44 UTC, NESOY approved these changes
나중에 종합리뷰로 서로 프로젝트에 대한 이해도를 높히는게 좋아보이네요 ㅎㅎ

2020-02-04 14:30 UTC, merged