news bulk upload
snack-news/Snack-BE pull request #180
Opened 2020-03-04 00:44 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- Picks 삭제
- News에서 Title과 Content의 빈값 허용
- NewsDto를 Array(List)로 받도록 변경 (for bulk upload)
   - JPA batch insert 미적용
- Collection으로 된 RequestBody를 Validate할 수 있도록 변경
   - 테스트 추가 예정

### Reference
- custom validation 관련
   - https://github.com/HomoEfficio/dev-tips/wiki/SpringMVC%EC%97%90%EC%84%9C-Collection%EC%9D%98-Validation
   - https://gompangs.tistory.com/entry/Spring-Valid-Collection-Validation-%EA%B4%80%EB%A0%A8
- validate 테스트 관련
   - https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/test/java/org/springframework/validation/beanvalidation/ValidatorFactoryTests.java

2020-03-04 00:46 UTC, vomvoru commented
Hey @Delf-Lee,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;658010036">View build log</a>

###### TravisBuddy Request Identifier: 92c2dca0-5db1-11ea-a4d3-d7a0e4bf840e

2020-03-04 13:06 UTC, NESOY requested changes

2020-03-04 13:06 UTC, NESOY commented on src/main/java/com/snack/news/SnackApplication.java
> +		} catch (Exception e) {
요런 부분은 debugging용이라 제거해주시면 좋을거같아요.

2020-03-04 13:06 UTC, NESOY commented on src/main/java/com/snack/news/controller/AdminController.java
> +	@Validated(NewsDto.class)
@Valid랑 @Validated를 둘 다 사용하신 이유가 있으실까요?

2020-03-04 13:06 UTC, NESOY commented on src/main/java/com/snack/news/domain/news/News.java
> +		// Optional.ofNullable(category).orElseThrow(NewsNotFoundException::new);
```suggestion
```

2020-03-04 13:06 UTC, NESOY commented on src/main/java/com/snack/news/exception/validator/CustomCollectionValidator.java
> +public class CustomCollectionValidator implements Validator {
이걸 사용하면 어떤 점이 더 좋을까요?

2020-03-04 14:52 UTC, Delf-Lee commented on src/main/java/com/snack/news/exception/validator/CustomCollectionValidator.java
> +public class CustomCollectionValidator implements Validator {
- bulk upload를 염두에 두고 NewsDto를 배열(List)로 받는다
- List는 JavaBean가 아니기 때문에 `javax.validation`의 `@Valid`로는 처리할 수 없다
   - NewsDto는 가능하지만 List<NewsDto>는 인식 불가
- 때문에 그룹 지정이 가능한 `org.springframework.validation`의 `@Validated`를 채택

2020-03-04 14:53 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/AdminController.java
> +	@Validated(NewsDto.class)
이상하게 파라미터쪽의 `@Valid`를 없애면 (혹은 `@Validated`로 바꾸면) 동작이 안되네요... 이 부분은 조금 더 봐야할 것 같습니다.

2020-03-05 14:46 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/AdminController.java
> +	@Validated(NewsDto.class)
제가 `@Validated`의 사용 방법을 잘못 알고 이용했었군요.
`Validator`를 직접 구현하고 메서드 내에서 BindingResult를 직접 제어하는 방법도 있지만, 단순히 제공되는 pointcut에서 예외를 잡고 advice로 예외를 핸들링하는 방법이 있었습니다.

- https://www.baeldung.com/spring-validate-list-controller

2020-03-09 12:15 UTC, NESOY approved these changes

2020-03-09 12:29 UTC, merged