Feature/slackbot
snack-news/Snack-BE pull request #189
Opened 2020-05-14 09:33 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- DB 저장 항목에 channelName 추가
- 채널 정보 삭제 기능 추가(이벤트 받기 + 사후처리)

2020-05-14 09:35 UTC, vomvoru commented
Hey @Delf-Lee,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;686931139">View build log</a>

###### TravisBuddy Request Identifier: 43f7fbd0-95c6-11ea-afc2-11f58fd47587

2020-05-14 09:35 UTC, NESOY commented on src/main/java/com/snack/news/repository/SlackBotRepository.java
> +import java.util.Iterator;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.util.Iterator'](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973)

2020-05-14 09:35 UTC, NESOY commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 5
           

Complexity increasing per file
==============================
- src/main/java/com/snack/news/service/SlackBotService.java  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973&bid=18099424)

2020-05-14 09:35 UTC, NESOY commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +	private TopicService topicService;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused private fields such as 'topicService'.](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973)

2020-05-14 09:35 UTC, NESOY commented on src/main/java/com/snack/news/repository/SlackBotRepository.java
> +import java.util.Iterator;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused import - java.util.Iterator.](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973)

2020-05-14 09:35 UTC, NESOY commented on src/main/java/com/snack/news/repository/SlackBotRepository.java
> +import java.util.List;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Unused import - java.util.List.](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973)

2020-05-14 09:35 UTC, NESOY commented on src/main/java/com/snack/news/repository/SlackBotRepository.java
> +import java.util.List;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused imports such as 'java.util.List'](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973)

2020-05-17 02:20 UTC, NESOY requested changes
코드 작성하느라 고생하셨습니다. :) 
사용하지 않는 import가 많이 보이는데 Spotless 적용하면 좋을거 같네요 :)
https://nesoy.github.io/articles/2020-04/Spotless

2020-05-17 02:20 UTC, NESOY commented on src/main/java/com/snack/news/controller/SlackBotController.java
>  @RestController
여기에는 없지만.. api가 "api/slackbot"이라는게 api가 slack에 너무 종속되지 않을까요?
- 다른 봇들이 추가가 되면 api / {xxxbot} 이렇게 하나하나 작성해가는게 좋을까요?

2020-05-17 02:20 UTC, NESOY commented on src/main/java/com/snack/news/service/SlackBotService.java
> +		for (String webhookUrl : webhookUrlList) {
List를 Parameter로 받는 함수가 없을까요?

2020-05-17 02:20 UTC, NESOY commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteSlackChannelByTeamId(body.get("team_id").toString());
여러번 호출해도 동일한 결과를 반환하나요? 아니면 여러번 호출할때 에러가 발생하나요?

2020-05-17 02:20 UTC, NESOY commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteInvalidSlackChannel(webhookUrlList);
여러번 호출해도 동일한 결과를 반환하나요? 아니면 여러번 호출할때 에러가 발생하나요?

2020-05-17 02:25 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteSlackChannelByTeamId(body.get("team_id").toString());
사용되는 메서드가 다 void라 반환값이 따로 없지만, slack event subscribe 특성상 요청이 한번만 오진 않기 때문에 반복되서 요청하더라도 오류가 발생하지는 않습니다.

DB관리(불필요 채널 정보 삭제)를 위해 고안한 방법 중 하나이지만, 사실 여러모로 빈틈이 많은 방법이라 아래의 사후처리 방법을 추가했습니다.

2020-05-17 02:29 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteInvalidSlackChannel(webhookUrlList);
이 요청은 제어가 되기 때문에 여러번 호출할 일은 드물지만, 역시 변수 값이 DB와 일치하지 않아도 따로 에러를 발생시키진 않습니다.

2020-05-17 02:29 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteInvalidSlackChannel(webhookUrlList);
물론 조치가 필요하다면 로그를 남길 수는 있겠네요ㅎㅎ

2020-05-18 06:37 UTC, Delf-Lee commented on src/main/java/com/snack/news/service/SlackBotService.java
> +		for (String webhookUrl : webhookUrlList) {
jpa query method keyword 단에서 지원하는건 없지만, 자체적으로 변경했습니다

2020-05-18 07:04 UTC, vomvoru commented
Hey @Delf-Lee,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;688253357">View build log</a>

###### TravisBuddy Request Identifier: c3cb2d70-98d5-11ea-ab7d-a3d971849d0e

2020-05-18 07:04 UTC, NESOY commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973&bid=18099424)

2020-05-18 07:04 UTC, NESOY commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +	private TopicService topicService;
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid unused private fields such as 'topicService'.](https://app.codacy.com/manual/snack-news/Snack-BE/pullRequest?prid=5523973)

2020-05-19 14:45 UTC, NESOY commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteInvalidSlackChannel(webhookUrlList);
요청이 제어가 된다라는건 사실 현재 상황인거 같은데.. API 설계하는데 있어서 요청이 제어가 된다는게.. 저로선 신기하네요 ㅎㅎ 
나중에 어떻게 누가 어떻게 호출될지에 대한 확장성을 고려하려면 위상황을 고려해야하지 않을까요?

2020-05-20 10:35 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
>  @RestController
그렇다면 /api/bot/slack 은 어떨까요?

2020-05-20 12:01 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
>  @RestController
다시 생각해보니 그러면 front에도 변경사항이 생기니 번거롭겠군요...
그런데 영재님의 제안대로 한다면 하나의 컨트롤러에서 여러 봇에 대한 요청을 처리해야하는 것 아닌가요?

2020-05-21 14:27 UTC, NESOY commented on src/main/java/com/snack/news/controller/SlackBotController.java
>  @RestController
@Delf-Lee 꼭 하나의 컨트롤러가 아닌 여러개의 컨트롤러일수도 있지 않을까요? ㅎㅎ
REST API 설계할때 자원의 개념으로 사용한다고 들었던거 같아요 ㅎㅎ 그래서 제안해봤습니다
- https://restfulapi.net/resource-naming/

2020-05-21 14:27 UTC, NESOY approved these changes

2020-05-22 00:27 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
>  @RestController
참고하겠습니다 😃

2020-05-22 00:31 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/SlackBotController.java
> +		slackBotService.deleteInvalidSlackChannel(webhookUrlList);
@NESOY 
이 코멘트를 늦게 발견했군요...
일단 시야를 넓혀준 것에 대해 감사합니다 :) 예상하셨다시피 "현재 상황"을 가정한게 맞습니다. 다만 아직까지는 과투자일 가능성이 높아보이네요.

지금 단계에서는 저 상황에서 오류 발생은 그다지 치명적이지 않습니다. 하지만 영재님 말씀대로 추후에 따로 예외를 처리해야할 수도 있으니 빠른 시일 내에 예외 핸들링 작업과 로깅을 추가하겠습니다.

2020-05-22 00:31 UTC, merged