Topic type에 대한 Topic list 요청에 대한 응답 구현
snack-news/Snack-BE pull request #22
Opened 2019-06-13 10:44 UTC by Delf-Lee

- Topic type에 대한 Topic list 요청에 대한 응답 구현
- Controller로 topic 요청시 TopicDto 객체 생성오류에 대한 문제 해결

2019-06-13 10:45 UTC, Delf-Lee commented
News리스트에 대한 내용은 반영되지 않았습니다. 이어서 테스트와 함께 올릴게요.

2019-06-13 10:45 UTC, Delf-Lee commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +	public void Topic_별로_뉴스를_조회할_수_있다() {
테스트 신뢰도와 효율을 위해 변경 여지 있음.

2019-06-17 05:34 UTC, NESOY requested changes
다음엔 조금 더 작게 요청 주시면 리뷰할때 더 좋을거 같아욥.

2019-06-17 05:34 UTC, NESOY commented on src/main/java/com/snack/news/controller/NewsController.java
>  	public List<News> getNews(@ModelAttribute NewsDto newsDto) {
`getNews`도 `getPeriodNewsList`처럼 자세하게 적으면 더 좋지 않을까요?

2019-06-17 05:34 UTC, NESOY commented on src/main/java/com/snack/news/domain/TopicType.java
> +	CORP, PERSON, FIELD, NONE;
`FIELD`는 무엇을 의미할까욥?

2019-06-17 12:29 UTC, Delf-Lee commented on src/main/java/com/snack/news/domain/TopicType.java
> +	CORP, PERSON, FIELD, NONE;
어느 "분야"라는 의미로 넣었습니다.

2019-06-17 16:21 UTC, merged