TopicController 테스트 추가
snack-news/Snack-BE pull request #23
Opened 2019-06-17 16:52 UTC by Delf-Lee

2019-06-18 06:48 UTC, NESOY requested changes

2019-06-18 06:48 UTC, NESOY commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +		Topic[] responseTopics = new Gson().fromJson(responseString, Topic[].class);
흠.. 이 부분은 GSON보다는 json-path가 더 어울릴거 같습니다 👍 

Reference
<https://tmondev.blog.me/220272188977>

2019-06-18 06:48 UTC, NESOY commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +	public void 토픽_생성_요청이_실패한다_타입_없음() throws Exception {
뭔가 문법이 외국문법으로 작성하신거같아요 ㅎㅎ

토픽 타입이 없다면 토픽 생성요청이 실패한다가 더 어울릴거 같습니다.

2019-06-18 06:48 UTC, NESOY commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +		final String url = "/api/topic";
굳이 URL을 따로 변수로 두신 이유가 있을까욥?

2019-06-18 09:27 UTC, Delf-Lee commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +		final String url = "/api/topic";
변수화 하려더가 되려 중복이 늘었네요. 필 변수로 올렸습니다.
이건 괜찮을까요?

2019-06-18 13:03 UTC, Delf-Lee commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +		Topic[] responseTopics = new Gson().fromJson(responseString, Topic[].class);
jsonpath의 표현으로 응답 List의 요소 수와 내용을 모두 비교할 있는건가요?
<!-- https://groups.google.com/forum/#!topic/gatling/jOCUe9Dd534 -->
단일 비교밖에 찾을 수 없네요...

혹시 갖고있는 관련 레퍼런스가 더 있다면 공유해주시면 감사하겠습니다 :)

(실패  예)
``` java
String realTopicListJson = new GsonBuilder().serializeNulls().create().toJson(realTopicList);

mockMvc.perform(get(TOPIC_API_URL + "/CORP"))
		.andExpect(status().isOk())
		.andExpect(jsonPath("$").value(realTopicListJson))
		.andReturn();
```

2019-06-19 05:46 UTC, NESOY commented on src/test/java/com/snack/news/controller/TopicControllerTest.java
> +		Topic[] responseTopics = new Gson().fromJson(responseString, Topic[].class);
## Reference
<https://meetup.toast.com/posts/124>

2019-06-19 07:42 UTC, NESOY approved these changes

2019-06-19 07:44 UTC, merged