토픽조건과 기간조건 중복 적용하여 뉴스 리스트 반환
snack-news/Snack-BE pull request #32
Opened 2019-06-26 23:17 UTC by Delf-Lee

- 동적 쿼리 적용하기 위하여 `Citeria`사용
   - 사용자 커스텀 쿼리를 만들기 위해서 `NewsRepositoryCustom `인터페이스와 `NewsRepositoryCustomImpl` 클래스 추가
   - 바뀐 로직에 따른 테스트 코드 추가
   - 통합된 로직에 따른 서비스 레이어 메서드 삭제 및 이름 변경

2019-06-26 23:17 UTC, Delf-Lee commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +		if (newsDto.getTopicIds() != null) {
null 체킹에 대한 리팩토링 필요

2019-06-26 23:18 UTC, Delf-Lee commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +			criteria.add(nr.join("topics").get("id").in(newsDto.getTopicIds()));
하드 코딩에 대한 리펙토링 필요
- 메타모델 API 적용

2019-06-26 23:18 UTC, Delf-Lee commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +						.stream()
stream 중첩에 대한 의심

2019-06-27 07:40 UTC, NESOY commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +		if (newsDto.getTopicIds() != null) {
굉장히 if문이 많네욥..?

2019-06-27 07:43 UTC, NESOY requested changes

2019-06-27 07:43 UTC, NESOY commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +				.filter(n -> n.getCreateAt().isBefore(end) && n.getCreateAt().isAfter(start))
filter의 && 보다는 두번의 filter가 가독성이 더 좋아보입니담.

2019-06-27 07:44 UTC, NESOY commented
혹시 CriteriaBuilder에 대한 참고 Reference를 받을 수 있을까요?

2019-06-27 08:04 UTC, Delf-Lee commented on src/main/java/com/snack/news/repository/NewsRepositoryImpl.java
> +		if (newsDto.getTopicIds() != null) {
그것도 해결해야할 문제 중 하나겠네요ㅎㅎ

2019-06-27 08:07 UTC, Delf-Lee commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +				.filter(n -> n.getCreateAt().isBefore(end) && n.getCreateAt().isAfter(start))
filter 두번쓰는건 속도의 차이가 없나요?

2019-06-27 08:13 UTC, NESOY commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +				.filter(n -> n.getCreateAt().isBefore(end) && n.getCreateAt().isAfter(start))
@Delf-Lee filter 두번 태우는게 속도가 느릴거라고 생각이 들지만..
큰 성능차이가 발생하지는 않을거 같습니다. 물론 측정하는게 정답이겠죱..?

실제 리얼 코드가 아니라 테스트 코드라서.. 속도에 크게 영향은 안 받을거 같습니다. :)

2019-06-27 08:14 UTC, NESOY commented
QueryDsl Reference
- <http://www.querydsl.com/static/querydsl/3.4.3/reference/ko-KR/html_single/>

2019-06-27 08:17 UTC, NESOY requested changes

2019-06-27 08:17 UTC, NESOY commented on src/main/java/com/snack/news/service/NewsService.java
> +	/*public List<News> getPeriodNewsList(NewsDto newsDto) {
주석은 최대한 빼주시면 감사하겠습니다 🙏

2019-06-27 08:28 UTC, NESOY commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +						.stream()
stream 중첩이 된다면 어떤게 문제가 될까요? 시원한 글이 없네요ㅠ

참고할만한 Reference입니다.
- <https://homoefficio.github.io/2016/06/26/for-loop-%EB%A5%BC-Stream-forEach-%EB%A1%9C-%EB%B0%94%EA%BE%B8%EC%A7%80-%EB%A7%90%EC%95%84%EC%95%BC-%ED%95%A0-3%EA%B0%80%EC%A7%80-%EC%9D%B4%EC%9C%A0/>

2019-06-27 08:28 UTC, NESOY commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +				.filter(n -> n.getCreateAt().isAfter(start))
👍

2019-06-27 08:45 UTC, Delf-Lee commented
> @Delf-Lee
> 혹시 CriteriaBuilder에 대한 참고 Reference를 받을 수 있을까요?

@NESOY 
저는 대략적인 개념은 책에서, 실직적인 구현부는 예제를 참고하면서 짜서 좋은 레퍼런스를 갖고 있지는 않네요..
일단 말할 수 있는건
- 객체지향 쿼리를 작성하려면 JPQL을 이용해야한다.
- Critera쿼리는 JPQL을 편하게 작성하도록 도와주는 API. 빌더클래스 모음
-그 쿼리를 생성하는 실질적인 클래스가 CriteriaBuilder입니다.

2019-06-27 08:52 UTC, NESOY approved these changes

2019-06-27 08:53 UTC, merged