NewsController, TopicController 응답 형식을 ResponseEntity로 변경
snack-news/Snack-BE pull request #55
Opened 2019-07-19 04:53 UTC by Delf-Lee

2019-07-24 09:17 UTC, Delf-Lee commented
#56 에 따라 요청 성공 시 ResponseEntity에 들어가는 데이터를 래핑

2019-07-25 04:48 UTC, Delf-Lee commented
다음 두 가지의 목적으로 지금까지의 코드를 작성했는데요.
1. 모든 정상 응답을 `data`로 한번 감싸자.
2. 컨트롤러에서 응답(반환) 타입을 명시하자.
3. 그 응답 타입을 깔끔하게 보이게 하자.

코드를 보니 문득, 각 컨트롤러의 반환 값이 `ResponseEntity<SomeObject>`에서 `SomeObject`를 명시해준게 문법상 의미가 없다는걸 발견했습니다. 오히려 어떤 클래스를 넣어도 에러가 나지 않는다는 점에서 조금 잘못된 코드라고 생각이 듭니다. (일단 잘 돌아는 갑니다)

`ResponseEntity<WrappedResponse<SomeObject>`로 변경하면 더 명확해지기는 하지만 지저분해지네요.

혹시 위의 1, 2, 3을 만족하는 방법이 있을까요?

2019-07-25 15:41 UTC, NESOY requested changes

2019-07-25 15:41 UTC, NESOY commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
noContent를 날리면 어떤 결과가 나오는지 확인할 수 있을까요?

2019-07-25 15:41 UTC, NESOY commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
WrappedResponse 형식을 유지하는지 아니면 그냥 Empty Response가 날아가는건지 궁금합니다 :)

2019-07-25 15:45 UTC, NESOY commented
`오히려 어떤 클래스를 넣어도 에러가 나지 않는다는 점에서 조금 잘못된 코드`
이 부분이 명확하게 이해가 되지 않습니다 ㅠㅠ
원하시는게 WrappedResponse<T>만 받을 수 있게 하고 싶다는 의도이신건가요?

2019-07-25 16:13 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
https://github.com/snack-news/Snack-BE/issues/56#issuecomment-514890273
status code 204에 `WrappedResponse`에 관계 없이 빈 페이로드가 포함된 응답을 보냅니다.

2019-07-25 16:27 UTC, Delf-Lee commented
@NESOY 
예를들아 현재 아래 세개의 코드는 문제 없이 **같은** 동작을 합니다.
``` java
@GetMapping("/{newsId}")
public ResponseEntity<News> getNews(@PathVariable Long newsId) { // <News>
	return WrappedResponse.ok(newsService.getNews(newsId));
}
```

``` java
@GetMapping("/{newsId}")
public ResponseEntity<Topic> getNews(@PathVariable Long newsId) { // <Topic> ???
	return WrappedResponse.ok(newsService.getNews(newsId));
}
```

``` java
@GetMapping("/{newsId}")
public ResponseEntity getNews(@PathVariable Long newsId) { // (nothing)
	return WrappedResponse.ok(newsService.getNews(newsId));
}
```

첫번째 코드블럭 처럼 <News>를 반환하도록 명확하게 보여주려는 것이 목적이었습니다. 
위처럼 동작하는 원인은 `WrappedResponse<T>`의 해당 메서드입니다. 문제 없을거라고 판단했지만, 경고를 띄워준 이유가 있었네요.

``` java
@SuppressWarnings("unchecked")
public static <T, R> ResponseEntity<R> ok(T body) {
	return (ResponseEntity<R>) ResponseEntity.ok(new Wrapper(body));
}
```

2019-07-26 01:03 UTC, NESOY commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
흠... 그 방향과 아니면 포맷은 유지하면서 빈값을 내려주는 방향 두가지가 있을거 같은데 어떤게 더 좋을까요?

2019-07-26 01:09 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
해당 코드를 확인하면 값을 확인하는 것에 의미가 없을텐데, 굳이 넣을 필요가 있을까요?
그렇게 길지 않다는 점과 통일성을 줄 수 있다는 면에서는 넣어도 상관은 없지만요.

2019-07-26 01:10 UTC, NESOY commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
받는 사람이 파싱하는 부분이 null이 발생할 가능성이 있을거 같습니다 ㅠ
물론.. http status code때문에 error로 catch될거같기는 합니다만.. 한번 확인해봐야겠네욥!

2019-07-26 01:46 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/NewsController.java
> +			return ResponseEntity.noContent().build();
https://github.com/snack-news/Snack-BE/issues/56#issuecomment-515274591
FE쪽의 의견입니다.

댓글 확인해주시면 컨버세이션 해결로 바꾸고 계속해서 진행할게요.

2019-07-27 10:33 UTC, merged