Feature/admin api
snack-news/Snack-BE pull request #89
Opened 2019-09-18 12:56 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- NewsController에서 Admin용 READ API 추가
   - 페이징 처리
- 관련 테스트 코드 추가 

### Reference
- https://www.popit.kr/spring-boot-jpa-페이징-api-만들기/
- https://gyumin-kim.github.io/optional-pathvariable/
- Optional과 선택적 매개변수
   - Optional을 메서드의 매개변수로 사용했을 시, InterlliJ에서 경고 발생
   - https://www.wangler.io/blog/2017/java8-optionals.html
   - http://dolszewski.com/java/java-optional-parameters/

2019-09-18 20:26 UTC, Delf-Lee commented
@NESOY 
Codacy가 한글 메서드명하고 assert문이 없는 테스트를 닥치는대로 잡아내고 있는데... 혹시 왜그런지 아시나요

2019-09-19 04:11 UTC, NESOY commented
@Delf-Lee Rule 재조정해야할꺼같네요! 그건 오늘 만나서 얘기 나누시죠 :)

2019-09-27 14:24 UTC, NESOY requested changes

2019-09-27 14:24 UTC, NESOY commented on src/main/java/com/snack/news/controller/AdminController.java
> +	public ResponseEntity<Page<News>> getNewsList(@SuppressWarnings("OptionalUsedAsFieldOrParameterType")
@SuppressWarnings를 없애는 방향은 없을까요?

2019-09-27 14:24 UTC, NESOY commented on src/main/java/com/snack/news/domain/base/BaseTimeEntity.java
> +	private LocalDateTime publicAt;
public보다는 publish가 좋지 않을까요?

2019-09-27 14:24 UTC, NESOY commented on src/main/java/com/snack/news/service/NewsService.java
> +	public Page<News> getNewsListForAdmin(int page) {
이렇게 Method에 표현하는것보단 `admin`이라는 패키지를 따로만드는건 어떨까요?
그래야 나중에 분리하기도 편할거같습니다 ㅎㅎ

2019-09-27 14:24 UTC, NESOY commented on src/test/java/com/snack/news/controller/AdminControllerTest.java
> +	private final static String ADMIN_API_URL = "/api/admin/news";
final static 상수는 최대한 상위로 Convention 부탁드립니다.

2019-09-27 14:26 UTC, NESOY commented on src/main/java/com/snack/news/controller/AdminController.java
> +	public ResponseEntity<Page<News>> getNewsList(@SuppressWarnings("OptionalUsedAsFieldOrParameterType")
> Optional을 메서드의 매개변수로 사용했을 시, InterlliJ에서 경고 발생

경고를 하는데 굳이 Optional Parameter는 회피하는 방향으로 하는게 좋을거 같습니다.

2019-09-27 14:27 UTC, Delf-Lee commented on src/main/java/com/snack/news/domain/base/BaseTimeEntity.java
> +	private LocalDateTime publicAt;
앗 이건 단순히 오타네요ㅎㅎ

2019-09-27 14:28 UTC, Delf-Lee commented on src/main/java/com/snack/news/controller/AdminController.java
> +	public ResponseEntity<Page<News>> getNewsList(@SuppressWarnings("OptionalUsedAsFieldOrParameterType")
논의했던데로 따로 분리하는게 좋아보입니다.
작업은 완료된 상태이며, 아래의 리뷰사항이랑 같이 올릴게요!

2019-09-29 11:36 UTC, NESOY commented on src/test/java/com/snack/news/service/NewsServiceTest.java
> +import static org.mockito.ArgumentMatchers.*;
사용하지 않는 import제거해주세요 :)

2019-10-03 10:32 UTC, vomvoru commented
## Travis tests have failed

Hey @Delf-Lee,
Please read the following log in order to understand the failure reason.
It'll be awesome if you fix what's wrong and commit the changes.


### 1st Build

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;jobs&#x2F;592985976">View build log</a>


<details>
  <summary>
    <strong>
     .&#x2F;gradlew clean build
    </strong>
  </summary>

```
> Task :clean
> Task :compileJava
> Task :processResources
> Task :classes
> Task :bootJar
> Task :jar SKIPPED
> Task :assemble

> Task :compileTestJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :processTestResources
> Task :testClasses

> Task :test

com.snack.news.controller.AdminControllerTest > 뉴스_생성_요청이_정상적으로_이루어진다 FAILED
    java.lang.AssertionError at AdminControllerTest.java:59

com.snack.news.controller.AdminControllerTest > 어드민_페이지에서_페이지를_지정하지_않는다면_1페이지를_가져온다 FAILED
    java.lang.AssertionError at AdminControllerTest.java:119

com.snack.news.controller.AdminControllerTest > 뉴스_생성_요청시_제목을_입력하지_않으면_BADREQUEST_상태코드로_응답한다 FAILED
    java.lang.AssertionError at AdminControllerTest.java:73

com.snack.news.controller.AdminControllerTest > 어드민_페이지에서_뉴스리스트를_정상적으로_가져온다 FAILED
    java.lang.AssertionError at AdminControllerTest.java:110

com.snack.news.controller.AdminControllerTest > 뉴스_생성_요청시_카테고리ID를_입력하지_않으면_BADREQUEST_상태코드로_응답한다 FAILED
    java.lang.AssertionError at AdminControllerTest.java:101

com.snack.news.controller.AdminControllerTest > 뉴스_생성_요청시_내용을_입력하지_않으면_BADREQUEST_상태코드로_응답한다 FAILED
    java.lang.AssertionError at AdminControllerTest.java:87
2019-10-03 10:31:29.623  INFO 4561 --- [       Thread-6] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-10-03 10:31:29.625  INFO 4561 --- [       Thread-6] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table category if exists
Hibernate: drop table news if exists
Hibernate: drop table news_tag if exists
Hibernate: drop table news_topic if exists
Hibernate: drop table tag if exists
Hibernate: drop table topic if exists
2019-10-03 10:31:29.662  INFO 4561 --- [      Thread-12] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-10-03 10:31:29.662  INFO 4561 --- [       Thread-9] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
2019-10-03 10:31:29.665  INFO 4561 --- [      Thread-12] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-10-03 10:31:29.666  INFO 4561 --- [      Thread-12] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table category if exists
2019-10-03 10:31:29.667  INFO 4561 --- [       Thread-9] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2019-10-03 10:31:29.682  INFO 4561 --- [       Thread-9] .SchemaDropperImpl$DelayedDropActionImpl : HHH000477: Starting delayed evictData of schema as part of SessionFactory shut-down'
Hibernate: drop table category if exists
Hibernate: drop table news if exists
Hibernate: drop table news_tag if exists
Hibernate: drop table news_topic if exists
Hibernate: drop table tag if exists
Hibernate: drop table topic if exists
Hibernate: drop table news if exists
Hibernate: drop table news_tag if exists
Hibernate: drop table news_topic if exists
Hibernate: drop table tag if exists
Hibernate: drop table topic if exists
2019-10-03 10:31:29.729  INFO 4561 --- [      Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown initiated...
2019-10-03 10:31:29.744  INFO 4561 --- [       Thread-9] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2019-10-03 10:31:29.763  INFO 4561 --- [      Thread-12] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown completed.
2019-10-03 10:31:29.765  INFO 4561 --- [       Thread-9] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

48 tests completed, 6 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///home/travis/build/snack-news/Snack-BE/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 36s
7 actionable tasks: 7 executed
```

</details>


###### TravisBuddy Request Identifier: 0d149270-e5c9-11e9-99fa-bd1133e3d0ce

2019-10-03 10:54 UTC, vomvoru commented
Hey @Delf-Lee,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;592992691">View build log</a>

###### TravisBuddy Request Identifier: 232c36a0-e5cc-11e9-99fa-bd1133e3d0ce

2019-10-03 10:56 UTC, vomvoru commented
Hey @Delf-Lee,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;592993411">View build log</a>

###### TravisBuddy Request Identifier: 679507e0-e5cc-11e9-99fa-bd1133e3d0ce

2019-10-03 11:01 UTC, merged