날짜검증 버그 수정 및 테스트 코드 추가
snack-news/Snack-BE pull request #90
Opened 2019-09-18 22:17 UTC by Delf-Lee

### 이런게 변경되었어요. 💍
- 날짜 검증 버그 수정
- **무조건 월요일로 시작**해야하던 조건을 **시작일이 월요일이거나 종료일이 일요일**인 조건으로 변경
- 로직에 해당하는 테스트 코드 추가

2019-09-27 14:18 UTC, NESOY requested changes

2019-09-27 14:18 UTC, NESOY commented on src/main/java/com/snack/news/dto/Period.java
> +		if (!start.getDayOfWeek().equals(DayOfWeek.MONDAY) && !end.getDayOfWeek().equals(DayOfWeek.SUNDAY)) {
설명에 `시작일이 월요일이거나 종료일이 일요일`라고 표현하셨는데

코드를 봤을때 너무 이해하기 어렵네요 ㅠㅠ 깔끔하게 표현할수 없을까요?
요구사항 다시 정의해주실수있을까요?

2019-09-27 14:18 UTC, NESOY commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		new Period(start, end).validationCheck();
검증코드가 없는데.. 의미있는 테스트일까요?

2019-09-27 14:18 UTC, NESOY commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		LocalDateTime start = LocalDateTime.of(2019, 7, 29, 0, 0); // 월
//월을 startOfMonday라고 표현하면 어떨까요?

2019-09-27 14:18 UTC, NESOY commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		new Period(start, end).validationCheck();
validationCheck보단 isValid라고 표현하는건 어떨까요?

2019-09-27 14:37 UTC, Delf-Lee commented on src/main/java/com/snack/news/dto/Period.java
> +		if (!start.getDayOfWeek().equals(DayOfWeek.MONDAY) && !end.getDayOfWeek().equals(DayOfWeek.SUNDAY)) {
의미상으로 가져간다면
``` java
if (!(start.getDayOfWeek().equals(DayOfWeek.MONDAY) || end.getDayOfWeek().equals(DayOfWeek.SUNDAY)) {...}
```

으로 표현할 수 있겠네요. 이건 어떤가요?

2019-09-27 14:41 UTC, Delf-Lee commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		new Period(start, end).validationCheck();
isValid라고 표현하기엔 리턴 값이 없다는 점에서 조금 의미가 어긋나지 않을까요?
그리고 리턴값이 없기에, 예외가 발생하지 않는다면 테스트 성공이지만 형식적으로 `assertThat(true);` 같은걸 넣는 것도 한 방법이겠네요.

2019-09-27 14:42 UTC, Delf-Lee commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		LocalDateTime start = LocalDateTime.of(2019, 7, 29, 0, 0); // 월
아 근데, 주석에서 카멜표기법을 쓰는 이유가 있나요?

2019-09-27 14:46 UTC, Delf-Lee commented on src/main/java/com/snack/news/dto/Period.java
> +		if (!start.getDayOfWeek().equals(DayOfWeek.MONDAY) && !end.getDayOfWeek().equals(DayOfWeek.SUNDAY)) {
이러면 깔끔해지긴 하겠네요!
``` java
if (!(isMonday(start) || isSunday(end))) {
	throw new NewsBadRequestException();
}
```

2019-09-29 11:32 UTC, NESOY commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		LocalDateTime start = LocalDateTime.of(2019, 7, 29, 0, 0); // 월
아 주석이 아니라 변수명입니다.

2019-09-29 11:33 UTC, NESOY commented on src/main/java/com/snack/news/dto/Period.java
> +		if (!start.getDayOfWeek().equals(DayOfWeek.MONDAY) && !end.getDayOfWeek().equals(DayOfWeek.SUNDAY)) {
훨씬 이해하기 쉬운 코드군요. :)

2019-09-29 11:35 UTC, NESOY commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		new Period(start, end).validationCheck();
흠.. 아니면 생성자에서 validationCheck를 하는건 어떨까요?
생성과 동시에 검증하는게 더 좋아보입니다 ㅎㅎ

테스트를 위해 assertThat(True)를 넣는것은 좋은 방법은 아닌거 같습니다.ㅠㅠ

2019-09-29 14:17 UTC, Delf-Lee commented on src/test/java/com/snack/news/dto/PeriodTest.java
> +		new Period(start, end).validationCheck();
생성자에서 검증하는게 딱히 상관은 없지만, 지금 코드에선 조금 곤란해집니다. 돌아가긴 하지만요.

- 현재 뉴스 리스트를 조회하는 과정에서 `new Period(start, end).validationchaeck();`를 수행
   - (NewsDto에서 Period를 갖고있는게 아님)
   - [코드](https://github.com/snack-news/Snack-BE/blob/master/src/main/java/com/snack/news/service/NewsService.java#L39)
- 생성자에서 검증하면 맥락상 뜬금없이 `new Period(start, end);`이 등장하게 되는 꼴
- NewsDto에서 필드로 Period를 갖고 있는 방법이 좋아보였으나, NewsDto가 꼭 뉴스 리스트 조회에만 사용되는게 아니므로, 불필요한 예외가 발생

날짜 검증 스펙에 대해서 FE팀한테 물어보고 다시 생각해봐야겠네요.
어쩌면 조회용 DTO를 따로 만들어보는 것도 고려해봐야 할 것 같습니다.

2019-10-04 14:12 UTC, vomvoru commented
Hey @Delf-Lee,  
Your changes look good to me!

<a href="https:&#x2F;&#x2F;travis-ci.org&#x2F;snack-news&#x2F;Snack-BE&#x2F;builds&#x2F;593564355">View build log</a>

###### TravisBuddy Request Identifier: fc2dbfc0-e6b0-11e9-80a6-e1456923af30

2019-10-04 14:13 UTC, merged